name: pre-release

on:
  push:

jobs:
  pre-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-darwin
            os: macos-14
          - target: aarch64-linux
            os: ubuntu-latest
          - target: armv6l-linux
            os: ubuntu-latest
          - target: armv7l-linux
            os: ubuntu-latest
          - target: i686-linux
            os: ubuntu-latest
          # FIXME
          # - target: i686-windows
          #   os: ubuntu-latest
          - target: x86_64-darwin
            os: macos-13
          - target: x86_64-linux
            os: ubuntu-latest
          - target: x86_64-windows
            os: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          enable_kvm: true
          extra_nix_config: experimental-features = nix-command flakes
      - name: Cache Nix store
        uses: cachix/cachix-action@v15
        with:
          name: soywod
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Build release
        run: nix build .#cross-${{ matrix.target }}
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: himalaya-${{ matrix.target }}
          path: result/bin/himalaya*
      - name: Upload share folder
        uses: actions/upload-artifact@v4
        if: ${{ matrix.target == 'x86_64-linux' }}
        with:
          name: share
          path: result/share
