name: Pre-releases

on:
  workflow_dispatch:
  push:
    branch: master

jobs:
  build:
    uses: pimalaya/nix/.github/workflows/pre-releases.yml@master
    secrets: inherit
    with:
      project: himalaya
